
  <div class="modal fade" id="local">
    <div class="modal-dialog modal-lg">
      <div class="modal-content">
      

        <div class="modal-header">
          <h6 class="modal-title">Nossa Lozalização: </h6>
          <br><p> R. Cel. Carlos Matos, 86 - Centro, Nova Iguaçu - RJ, 26210-200</p>
          <button type="button" class="close" data-dismiss="modal">&times;</button>
        </div>
        

        <div class="modal-body">
          <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3679.263254530684!2d-43.451972099498875!3d-22.755609594728117!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x9967a99225f96f%3A0xec20bfc8ff090b46!2sSENAC+Nova+Igua%C3%A7u!5e0!3m2!1spt-BR!2sbr!4v1519269670636" width="100%" height="450" frameborder="0" style="border:0" allowfullscreen></iframe>

<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBu-916DdpKAjTmJNIgngS6HL_kDIKU0aU&callback=myMap"></script>
        </div>
        
        <div class="modal-footer">
        </div>
        
      </div>
    </div>
  </div>